baseURL: "/"
languageCode: "en-us"
title: "Richard Martin"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/richdmartin"
  github: "https://github.com/richdmartin13"
  instagram: "https://instagram.com/richdmartin13"
  linkedin: "https://linkedin.com/in/richdmartin"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
